### ISSUE TITLE
Products

### ISSUE THREAD

**Issue by rahulan** [danielschmitz/svelte-sapper-bulma-crud#2]
Hi, 
I tried to create a new product, which broke the Products page. Please delete my entry.
Sorry for the hassle. Thank you.

![https___northwind_now_sh_api_products](https://user-images.githubusercontent.com/28999/58304841-e12c2a80-7ded-11e9-9dbc-5985d3f2d5fb.png)

**Comment by danielschmitz** [comment]
np. done!
